--- 
- hosts: all 
  become: yes 
  tasks:
  - name: i want to install webserver on ubuntu
    apt: 
      name: apache2 
      state: persent 

  - name: i want to install webserver on ubuntu
    service: 
      name: apache2 
      state: startd   