--- 
- hosts: all 
  become: yes 
  tasks:
  - name: i want to install webserver on ubuntu
    apt: 
      name: apache2 
      state: persent 
    when: ansible_os_family-=="Debian"

  - name: i want to install webserver on ubuntu
    service: 
      name: apache2 
      state: started   
    when: ansible_os_family-=="Debian"