--- 
- hosts: 172.31.38.215
  become: yes 
  tasks: 
  - name: i want execute linux command
    command: hostname -f 
    register: myfirsttaskresult
  
  - name: i want to display my first task result 
    debug: 
      msg: "{{myfirsttaskresult}}"