--- 
- hosts: 172.31.38.215 
  become: yes 
  tasks: 
  - name: install git 
    apt: 
     name: git 
     state: present 

  - name: install tree 
    apt: 
      name: tree 
      statrre: present 

  - name: install wget
    apt: 
      name: wget 
      statrre: present         