--- 
- hosts: 172.31.38.215 
  become: yes 
  tasks: 
  - include_tasks: myfilee.yml

  - name: install webserver
    apt: 
     name: apache2
    notify: restartwebserver

  - name: i want to copy static file into ansible nodes 
    copy: 
     src: mystatic.txt
     dest: /home/ubuntu/mystatic.txt 
    notify: restartwebserver

  - name: i want to copy dyno file into ansible nodes   
    template:
       src: mydynofile.j2
       dest: /var/www/html/index.html 
    notify: restartwebserver

  - name: i want to download remote files inot ansible nodes 
    get_url: 
      url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.15/bin/apache-tomcat-8.0.15.tar.gz
      dest: /home/ubuntu/apache-tomcat-8.0.15.tar.gz
      force_basic_auth: yes
    notify: restartwebserver  
    
  handlers: 
  - name: restartwebserver 
    service: 
       name: apache2 
       state: restart 


     
