--- 
- hosts: 172.31.38.215 
  become: yes 
  tasks: 
  - include_tasks: myfile.yml 
  - name: install webserver
    apt: 
     name: apache2
  - name: i want to copy static file into ansible nodes 
    copy: 
     src: mystatic.txt
     dest: /home/ubuntu/mystatic.txt 
     

  